from enum import IntEnum
class CandlestickPattern(IntEnum):
	HAMMER = 0
	BULLISH_ENGULF = 1
	THREE_WHITE_SOLDIERS = 2
	THREE_INSIDE_UP = 3
	THREE_INSIDE_DOWN = 4
	EVENING_STAR = 5
	BEARISH_ENGULFING = 6
	THREE_BLACK_CROWS = 7
	IS_MORNING_STAR = 8
	HANGING_MAN = 9
